FROM prefecthq/prefect:3-latest

WORKDIR /root/open-energy-data-server

RUN apt-get update && apt-get install -y build-essential git && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt